### ISSUE TITLE
getpage Snippet

### ISSUE THREAD

**Issue by lilaoli** [kauemurakami/getx_snippets_extension#6]
I tried your snippets and I like your idea to create coherent patterns and appreciate your work very much.

So I created a basic test scenario only with snippets: 
I created an API class with getprovider,
a repository class with getrepository,
a controller class with getcontroller,
and finally a page class with getpage. 

Everything fits together well. Except the page class! Here is a warning: 

```
class TestPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('TestPage')),
      body: Container(
        child: GetX<TestController>(
            init: TestController(),            <---      Warning: The parameter 'repository' is required!
            builder: (_) {
              return Container();
            }),
      ),
    );
  }
} 
```

For some reasons I don't like to define a repository and the required parameter an API class on the page.
Do you have some ideas or suggestions to solve this issue like a standard pattern.
Thank you!

**Comment by kauemurakami** [comment]
Good morning lilaloli, first, thank you for contributing to the project.
There are two ways to resolve this.
First, every controller has a constructor like this>
MyController extends GetxController {
final MyRepository repository;
MyController ({@ required this.repository}): assert (repository! = Null);
...
}
This is because, generally, we use one or more repositories in a controller.
The repository, in turn, has a mandatory parameter of
MyRepository {
final MyApiClass api;
MyRepository ({@ required api}): assert (api! = Null);
}
Repositories, made to abstract your entities, need your api object, just as your controller needs your repository object.
And your api class, should follow the same pattern expecting an http, or hate, object of your preference.
So now for solutions;
1 - In your case, initm should have something like:
init: TestController (
MyRepository (MyApiClass (httpClient: http.Client ()))
),
This would solve your problem.
another way is to use bindings, to make your page cleaner with GetView <YourController>, initializing everything with bindings.
The example in the pattern I think we managed to help you, and this week we’re going to raise a bigger one.
Another solution, if you are not going to make connections, and want to initialize it all by your own class, just remove the finals, so you don't need constructors.
How would it look with GetView <YourController>?
class TestPage extends GetView <TestController> {
  @override
  Build widget (BuildContext context) {
    return Scaffold (
      appBar: AppBar (title: Text ('TestPage')),
      body: Container (
        child: GetX <TestController> (
         
            builder: (_) =>
          Text (controller.textExample);
),
      ),
    );
  }
}

For this you will need another file in your module, this serves to make your view cleaner.
would be like this
class TestBinding implements Bindings {
  @override
  void dependencies () {
    Get.lazyPut <TestController> (() => TestController (
        repository:
            TestRepository (apiClient: MyApuClass (httpClient: http.Client ()))));
  }
}
Where controller receives the repository, the repository receives the api, which is passed to the last class.
If the doubt persists I will leave the topic open for today.

**Comment by kauemurakami** [comment]
Exactly, but be careful, you won't always be able to use the GetX widget, so don't init init. The bindings part will help you to manage your dependencies in a more pleasant and organized way. Regarding the suggestions, I will be improving this as soon as possible. Thanks for contributing, any questions just call. !!!!
